// prettier-ignore
import { FaAppleAlt, FaExclamationTriangle, FaGlassWhiskey, FaGrinTongue, FaGripLines, FaRunning, FaSadTear, FaSearch, FaUniversity } from "react-icons/fa";
// prettier-ignore
import { FaAnchor, FaBacon, FaBars, FaBicycle, FaBolt, FaBowlRice, FaCarBattery, FaCat, FaChessKing, FaCity, FaCoins, FaComment, FaCommentDots, FaCouch, FaDatabase, FaDoorOpen, FaFeather, FaFire, FaGavel, FaGun, FaImage, FaIndustry, FaKey, FaLanguage, FaLeaf, FaLightbulb, FaMountain, FaNotesMedical, FaRulerCombined, FaSailboat, FaShirt, FaSitemap, FaStar, FaTable, FaUser, FaUsers, FaUsersGear, FaUserShield, FaUserTie, FaWater } from "react-icons/fa6";

export const iconsList = {
  warning: <FaExclamationTriangle />,
  gripLines: <FaGripLines />,
  bars: <FaBars />,
  university: <FaUniversity />,
  couch: <FaCouch />,
  database: <FaDatabase />,
  leaf: <FaLeaf />,
  rulerCombined: <FaRulerCombined />,
  industry: <FaIndustry />,
  image: <FaImage />,
  table: <FaTable />,
  bicycle: <FaBicycle />,
  city: <FaCity />,
  coins: <FaCoins />,
  comment: <FaComment />,
  language: <FaLanguage />,
  water: <FaWater />,
  tongue: <FaGrinTongue />,
  search: <FaSearch />,
  users: <FaUsers />,
  lightbulb: <FaLightbulb />,
  doorOpen: <FaDoorOpen />,
  bolt: <FaBolt />,
  key: <FaKey />,
  commentDots: <FaCommentDots />,
  userTie: <FaUserTie />,
  anchor: <FaAnchor />,
  mountain: <FaMountain />,
  userShield: <FaUserShield />,
  fire: <FaFire />,
  carBattery: <FaCarBattery />,
  cat: <FaCat />,
  user: <FaUser />,
  chessKing: <FaChessKing />,
  feather: <FaFeather />,
  sadTear: <FaSadTear />,
  gavel: <FaGavel />,
  notesMedical: <FaNotesMedical />,
  bacon: <FaBacon />,
  star: <FaStar />,
  gun: <FaGun />,
  running: <FaRunning />,
  sitemap: <FaSitemap />,
  appleAlt: <FaAppleAlt />,
  shirt: <FaShirt />,
  glassWhiskey: <FaGlassWhiskey />,
  bowlRice: <FaBowlRice />,
  sailboat: <FaSailboat />,
  usersGear: <FaUsersGear />,
};
